Remove tx util
Synthetixio/staking pull request #1194
Opened 2022-07-27 15:16 UTC by bachstatter

ToggleDelegateApprovals was no the only place where we used `import { tx } from 'utils/transactions';`.
Refactored that to the `useSynthetixQueries` and removed that module

2022-07-27 22:29 UTC, jmzwar requested changes

2022-07-27 22:29 UTC, jmzwar commented on sections/loans/components/ActionBox/ActiveBorrowsTab/ModifyLoanActions/Close.tsx
> +			console.log('hej');
Is this a swedish word :P

2022-07-27 23:13 UTC, noisekit approved these changes

2022-07-28 08:37 UTC, bachstatter commented on sections/loans/components/ActionBox/ActiveBorrowsTab/ModifyLoanActions/Close.tsx
> +			console.log('hej');
hehe opsi.. means hello

2022-07-28 08:38 UTC, bachstatter commented on sections/delegate/ToggleDelegateApproval.tsx
> +				await sleep(5000); // wait for the subgraph to sync
Yea I know. This table have a little refresh button and a tooltip too..

2022-07-28 12:21 UTC, merged