add a fallback for zapper list
Synthetixio/staking pull request #562
Opened 2021-06-01 06:22 UTC by andytcf

2021-06-01 06:51 UTC, vbstreetz requested changes
Added a comment but looking good.

2021-06-01 06:51 UTC, vbstreetz commented on queries/tokenLists/useZapperTokenList.ts
> +			const response = await axios.get<TokenListResponse>(EXTERNAL_LINKS.TokenLists.OneInch);
Should this remain as is?

2021-06-01 06:52 UTC, andytcf commented on queries/tokenLists/useZapperTokenList.ts
> +			const response = await axios.get<TokenListResponse>(EXTERNAL_LINKS.TokenLists.OneInch);
ah yes it should

2021-06-02 13:46 UTC, vbstreetz approved these changes
looks good 👍🏽

2021-06-03 07:16 UTC, merged