onBehalf logic added
Synthetixio/staking pull request #616
Opened 2021-07-07 07:33 UTC by clementbalestrat

<img width="679" alt="Screen Shot 2021-07-07 at 5 31 39 pm" src="https://user-images.githubusercontent.com/690350/124718377-641a8b80-df49-11eb-9aef-ecc5a39638e0.png">
<img width="224" alt="Screen Shot 2021-07-07 at 5 31 13 pm" src="https://user-images.githubusercontent.com/690350/124718387-67157c00-df49-11eb-951e-4f78c7fb40da.png">

2021-07-07 22:08 UTC, JChiaramonte7 approved these changes
LGTM

2021-07-08 05:31 UTC, andytcf requested changes
Left some fixes as comments

2021-07-08 05:31 UTC, andytcf commented on queries/delegate/useGetDelegateWallets.ts
> +			const { delegatedWallets } = await request(
haha @clementbalestrat, have we ditched the old  pageResults now

2021-07-08 05:31 UTC, andytcf commented on queries/delegate/useGetDelegateWallets.ts
> +			enabled: isAppReady && !isL2,
@clementbalestrat might want to check for ```walletAddress !== ''```

2021-07-08 05:31 UTC, andytcf commented on queries/delegate/useGetDelegateWallets.ts
> +			enabled: isAppReady && !isL2,
or ```isWalletConnected```

2021-07-08 05:31 UTC, andytcf commented on sections/shared/modals/WalletOptionsModal/WalletOptionsModal.tsx
> +					{delegateWallet && (
We should consider making the text have a defined width so the icons line up 

![image](https://user-images.githubusercontent.com/39738607/124866812-5542e000-e000-11eb-9134-717a84d9dc33.png)

2021-07-08 05:31 UTC, andytcf commented on sections/staking/components/BurnTab/BurnTab.tsx
> +							  });
L: 291 missing delegateWallet in useCallback dependencies

2021-07-08 05:31 UTC, andytcf commented on sections/staking/components/StakingInput/StakingInput.tsx
> +	const delegateWallet = useRecoilValue(delegateWalletState);
this ```delegateWallet``` is not used

2021-07-08 05:31 UTC, andytcf commented on translations/en.json
> +			"stop-delegation": "Stop delegation",
i think it should be "stop delegate mode"

2021-07-08 07:09 UTC, andytcf commented
@clementbalestrat 

small change about off-centered 

![image](https://user-images.githubusercontent.com/39738607/124878285-46aff500-e00f-11eb-99d5-5f8288507d39.png)

2021-07-08 07:19 UTC, andytcf commented
# Checklist 

Flows tested

- [ ] With "all" delegation given, the delegator is able to mint custom
- [ ] NOTE: Revoked "all" delegation from the delegator, when logged in as a delegator, the wallet still appears in the delegate select modal
- [ ] With no permissions granted, minting shows the correct error, burning shows the correct error and claiming shows the correct error


Flows not tested due to time

- [ ] Burning works

2021-07-14 23:53 UTC, drptbl commented
Issues:
-  Revoked "all" delegation from the delegator, when logged in as a delegator, the wallet still appears in the delegate select modal
- There is no way to remove a wallet completely from delegation list after you add it (you can only revoke it's delegations, but not remove it completely from the list)
<img width="408" alt="Screenshot 2021-07-15 at 00 48 50" src="https://user-images.githubusercontent.com/8177587/125702689-71bfcf25-ac47-4d57-ac8d-68a2ebed1e15.png">
- Unhandled errors after going to "Burn max" right after minting
<img width="1792" alt="Screenshot_2021-07-15_at_01 25 09" src="https://user-images.githubusercontent.com/8177587/125705497-af46a39c-0a4f-470b-bdd8-9de2f50c2359.png">
- UI is glitched because of very long error message in the button on "Burn custom":
<img width="1786" alt="Screenshot_2021-07-15_at_01 26 47" src="https://user-images.githubusercontent.com/8177587/125705533-458549f9-8c95-4cb7-b4b4-e431731931fb.png">

2021-07-15 07:07 UTC, vbstreetz approved these changes
Looking good 👍🏽. Would be cool to retain kovan support though.

2021-07-15 07:09 UTC, clementbalestrat commented
> Looking good 👍🏽. Would be cool to retain kovan support though.

Yeah we'll put it back once we have a testnet support with the Graph

2021-07-15 07:10 UTC, vbstreetz commented
> > Looking good 👍🏽. Would be cool to retain kovan support though.
> 
> Yeah we'll put it back once we have a testnet support with the Graph

Awesome 👍🏽

2021-07-15 07:11 UTC, vbstreetz commented
> > > Looking good 👍🏽. Would be cool to retain kovan support though.
> > 
> > 
> > Yeah we'll put it back once we have a testnet support with the Graph
> 
> Awesome 👍🏽

Wait, what did you mean exactly? since thegraph do support kovan etc...

2021-07-15 07:13 UTC, clementbalestrat commented
> > > > Looking good 👍🏽. Would be cool to retain kovan support though.
> > > 
> > > 
> > > Yeah we'll put it back once we have a testnet support with the Graph
> > 
> > 
> > Awesome 👍🏽
> 
> Wait, what did you mean exactly? since thegraph do support kovan etc...

Yes but synthetix subgraphes are only on Mainnet for now.

2021-07-15 22:33 UTC, drptbl commented
Everything has been fixed,

1 more issue:
- it would be great to redirect an user away from a page which he can't access while in delegation mode

2021-07-15 22:34 UTC, drptbl approved these changes

2021-07-16 02:25 UTC, merged